-- CREATE DATABASE "BlogLagbeV2";

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	"firstName" VARCHAR(15) NOT NULL,
	"lastName" VARCHAR(15) NOT NULL,
	username VARCHAR(30) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL CHECK(POSITION('@' IN email) > 0),
	password VARCHAR(255) NOT NULL,
	bio VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS blogs (
	id SERIAL PRIMARY KEY,
	"userId" SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	title VARCHAR(255) NOT NULL UNIQUE,
	content TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "comments" (
	id SERIAL PRIMARY KEY,
	"userId" SERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	"blogId" SERIAL NOT NULL REFERENCES blogs(id) ON DELETE CASCADE,
	content TEXT NOT NULL
);